<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160219192116 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		
		$this->addSql("CREATE TABLE IF NOT EXISTS arm_armcontest_domain_model_user (persistence_object_identifier varchar(40) COLLATE utf8_unicode_ci NOT NULL, stripeaccount varchar(255) COLLATE utf8_unicode_ci NOT NULL, PRIMARY KEY (persistence_object_identifier)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci");
		$this->addSql("CREATE TABLE IF NOT EXISTS `arm_armcontest_domain_model_contest` ( `persistence_object_identifier` varchar(40) COLLATE utf8_unicode_ci NOT NULL,  `name` varchar(150) COLLATE utf8_unicode_ci NOT NULL,  `description` longtext COLLATE utf8_unicode_ci NOT NULL,  `voting` tinyint(1) NOT NULL,  `submission` tinyint(1) NOT NULL,  PRIMARY KEY (`persistence_object_identifier`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci");
		$this->addSql("CREATE TABLE IF NOT EXISTS `arm_armcontest_domain_model_comment` (`persistence_object_identifier` varchar(40) COLLATE utf8_unicode_ci NOT NULL,  `artwork` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,  `user` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,  `comment` longtext COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`persistence_object_identifier`),  KEY `IDX_7810DB5A881FC576` (`artwork`),  KEY `IDX_7810DB5A8D93D649` (`user`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci");
		$this->addSql("CREATE TABLE IF NOT EXISTS `arm_armcontest_domain_model_artwork` (`persistence_object_identifier` varchar(40) COLLATE utf8_unicode_ci NOT NULL, `contest` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL, `name` varchar(150) COLLATE utf8_unicode_ci NOT NULL, `description` longtext COLLATE utf8_unicode_ci NOT NULL, `file` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL, `vote` int(11) NOT NULL, `approved` tinyint(1) NOT NULL, PRIMARY KEY (`persistence_object_identifier`), UNIQUE KEY `UNIQ_647B4C408C9F3610` (`file`), KEY `IDX_647B4C401A95CB5` (`contest`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci");
		
		$this->addSql("ALTER TABLE `arm_armcontest_domain_model_user` ADD CONSTRAINT `FK_3584979647A46B0A` FOREIGN KEY (`persistence_object_identifier`) REFERENCES `typo3_party_domain_model_abstractparty` (`persistence_object_identifier`) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE `arm_armcontest_domain_model_comment` ADD CONSTRAINT `FK_7810DB5A8D93D649` FOREIGN KEY (`user`) REFERENCES `arm_armcontest_domain_model_user` (`persistence_object_identifier`)");
		$this->addSql("ALTER TABLE `arm_armcontest_domain_model_comment` ADD CONSTRAINT `FK_7810DB5A881FC576` FOREIGN KEY (`artwork`) REFERENCES `arm_armcontest_domain_model_artwork` (`persistence_object_identifier`)");
		$this->addSql("ALTER TABLE `arm_armcontest_domain_model_artwork` ADD CONSTRAINT `FK_647B4C408C9F3610` FOREIGN KEY (`file`) REFERENCES `typo3_media_domain_model_image` (`persistence_object_identifier`)");
		$this->addSql("ALTER TABLE `arm_armcontest_domain_model_artwork` ADD CONSTRAINT `FK_647B4C401A95CB5` FOREIGN KEY (`contest`) REFERENCES `arm_armcontest_domain_model_contest` (`persistence_object_identifier`)");
	
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE `arm_armcontest_domain_model_artwork` DROP FOREIGN KEY FK_647B4C401A95CB5");
		$this->addSql("ALTER TABLE `arm_armcontest_domain_model_artwork` DROP FOREIGN KEY FK_647B4C408C9F3610");
		$this->addSql("ALTER TABLE `arm_armcontest_domain_model_comment` DROP FOREIGN KEY FK_7810DB5A8D93D649");
		$this->addSql("ALTER TABLE arm_armcontest_domain_model_comment DROP FOREIGN KEY FK_7810DB5A881FC576");
		$this->addSql("ALTER TABLE `arm_armcontest_domain_model_user` DROP FOREIGN KEY FK_3584979647A46B0A");
		
		$this->addSql("DROP TABLE arm_armcontest_domain_model_artwork");
		$this->addSql("DROP TABLE arm_armcontest_domain_model_comment");
		$this->addSql("DROP TABLE arm_armcontest_domain_model_user");
		$this->addSql("DROP TABLE arm_armcontest_domain_model_contest");
	}
}