
-
  name: 'Homepage'
  uriPattern: 'armcontest'
  defaults:
    '@package': 'ARM.Armcontest'
    '@controller': 'Standard'
    '@action': 'index'
    '@format': 'html'

-
   name: 'Artwork'
   uriPattern: 'armcontest/artworks/<ArtSubRoutes>'
   defaults:
     '@package': 'ARM.Armcontest'
     '@controller': 'Artwork'
     '@action': 'index'
     '@format': 'html'
   subRoutes:
    'ArtSubRoutes':
      package: 'ARM.Armcontest'
      suffix: 'Art'

-
   name: 'Contest'
   uriPattern: 'armcontest/contest/<ContestSubRoutes>'
   defaults:
     '@package':    'ARM.Armcontest'
     '@controller': 'Contest'
     '@action': 'index'
     '@format': 'html'
   subRoutes:
    'ContestSubRoutes':
      package: 'ARM.Armcontest'
      suffix: 'Contest'
